name: Issue labeler
on:
  issues:
    types: [ opened ]

permissions:
  contents: read

jobs:
  label-component:
    runs-on: ubuntu-latest

    permissions:
      issues: write

    steps:
      - uses: actions/checkout@v4

      - name: Parse issue form EN
        uses: stefanbuck/github-issue-parser@v3
        id: issue-parser-en
        with:
          template-path: .github/ISSUE_TEMPLATE/FormBugReportEN.yml

      - name: Parse issue form PT
        uses: stefanbuck/github-issue-parser@v3
        id: issue-parser-pt
        with:
          template-path: .github/ISSUE_TEMPLATE/FormBugReportPT.yml

      - name: Set labels of form-report-en
        uses: redhat-plumbers-in-action/advanced-issue-labeler@v3
        with:
          issue-form: ${{ steps.issue-parser-en.outputs.jsonString }}
          token: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true

      - name: Set labels of form-report-pt
        uses: redhat-plumbers-in-action/advanced-issue-labeler@v3
        with:
          issue-form: ${{ steps.issue-parser-pt.outputs.jsonString }}
          token: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true
